import { defineConfig } from 'vitepress'

export default defineConfig({
  title: "Claude's Memory",
  description: "An honest self-evaluation of Claude's training and capabilities",
  base: '/claude-memory/',

  head: [
    ['link', { rel: 'icon', href: '/favicon.ico' }]
  ],

  themeConfig: {
    logo: '/logo.svg',

    nav: [
      { text: 'Home', link: '/' },
      { text: 'Knowledge', link: '/knowledge-assessment' },
      { text: 'UI Frameworks', link: '/ui-frameworks-ranking' }
    ],

    sidebar: [
      {
        text: 'About Claude',
        items: [
          { text: 'Knowledge Assessment', link: '/knowledge-assessment' },
          { text: 'UI Frameworks Ranking', link: '/ui-frameworks-ranking' }
        ]
      }
    ],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/anthropics' }
    ],

    footer: {
      message: 'Generated by Claude (Opus 4.5)',
      copyright: 'December 2025'
    }
  }
})
